### PR TITLE
Fix errors and introduce phpstan

### PR DESCRIPTION
**Pull request by szepeviktor**
@polevaultweb You also added `$expires`

### CODE REVIEW

**Comment by rosswintle** [comment]
Hi Viktor, 

I'm working at Delicious Brains now. Looks like no one ever replied about your contribution, so first of all, THANK YOU!

I've just completed a major refactor of this package that should fix a bunch of things and set us up from some other features we want to add.

I'd love to get some tests in here, and do static analysis too. There are competing priorities, but I hope we can eventually do this. As this package is concerned with auth it does seem like automated checks on the intergrity of the code are particularly useful here (though I'm a proponent of static analysis anyway).

So, again, thank you. I'll try to pick this up in the future sometime!

If you use the package anywhere then please note the update and let me know if you have any problems.

**Comment by szepeviktor** [comment]
> If you use the package

Hello Ross! My PR-s are mostly inspirational, I do not develop software, just watching others and thinking about long-term sustainability.

**Comment by szepeviktor** [comment]
> I do not develop software

Although many are sure that I do!

**Comment by rosswintle** [comment]
Well I'm inspired, so thank you! 🙏

**Pull request closed without merging**
